#DROP temp

DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS technicians;
DROP TABLE IF EXISTS meter_codes;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS program_types;
DROP TABLE IF EXISTS problem_codes;
DROP TABLE IF EXISTS correction_codes;
DROP TABLE IF EXISTS location_codes;
DROP TABLE IF EXISTS reason_codes;
DROP TABLE IF EXISTS call_types;
DROP TABLE IF EXISTS serials;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS service_meters;
DROP TABLE IF EXISTS service_parts;
DROP TABLE IF EXISTS billing_meters;